name: Jest

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.sha }}

      - run: ./.github/scripts/test.sh

      - run: echo ${{ env.TESTVAR }}

