name: Jest

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - run: |
          echo "PR_BRANCH=$(curl -H "Accept: application/vnd.github.v3+json" ${{ github.event.issue.pull_request.url }} | jq '.head.ref')" >> $GITHUB_ENV

      - run: echo ${{ env.PR_BRANCH }}