name: Jest

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - run: |
          PR_DATA=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            ${GITHUB_API_URL}/repos/${{ github.event.issue.pull_request.url }}
          )

          echo ${PR_DATA}
          echo ${PR_DATA} | jq '.head.ref'
