name: PR tests

on:
  pull_request:
    branches: [main]
  issue_comment:
    types: [created]

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: $github
      run: echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

  testprcomments:
    name: Test @toptal-bot run comments
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (
        github.event_name == 'issue_comment' &&
        contains(github.event.comment.html_url, '/pull/') &&
        contains(github.event.comment.body, '@toptal-bot run') &&
        (
          contains(github.event.comment.body, 'test') ||
          contains(github.event.comment.body, 'all')
        )
      )

    steps:
      - run: echo "Should run always"

      - name: Set pending status
        if: github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/')
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: token ${{ github.token }}' \
          --header 'content-type: application/json' \
          --data '{ "state": "pending", "context": "ci/tests" }'
        
      - run: echo "Should run on PR comment"
        if: github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/')

      - run: echo "Should NOT run on PR comment"
        if: github.event_name != 'issue_comment'
      
      - run: sleep 59

      - name: Set success status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: token ${{ github.token }}' \
          --header 'content-type: application/json' \
          --data '{ "state": "success", "target_url": "https://example.com/build/status", "description": "The tests succeeded!", "context": "ci/tests" }'
        if: success() && github.event_name == 'issue_comment' && contains(github.event.comment.html_url, '/pull/')
