name: Jest

on:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GIT_BRANCH=${{ github.ref }}" >> $GITHUB_ENV
      - run: echo ${GIT_BRANCH#refs/heads/}
