name: PR tests

on:
  pull_request:
    branches: [master]
  issue_comment:
    types: [created]

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: $github
      run:   echo "$GITHUB_CONTEXT"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

  testprcomments:
    name: Test @toptal-bot run comments
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      contains(github.event.comment.html_url, '/pull/') &&
      (
        contains(github.event.comment.body, '@toptal-bot run') &&
        (
          contains(github.event.comment.body, 'test') ||
          contains(github.event.comment.body, 'all')
        )
      )

    steps:
      - run: echo "Should run always"

      - name: Report pending status
        if: github.event.action == 'comment' && contains(github.event.comment.html_url, '/pull/')
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.event.repository.owner }}/${{ github.event.repository.name }}/statuses/${{ github.sha }} \
          --header 'authorization: token ${{ secrets.TOPTAL_DEVBOT_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{ "state": "pending", "context": "ci/tests" }'
        
      - run: echo "Should run on PR comment"
        if: github.event.action == 'comment'

      - run: echo "Should NOT run on PR comment"
        if: github.event.action != 'comment'

      - name: Report success
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.event.repository.owner }}/${{ github.event.repository.name }}/statuses/${{ github.sha }} \
          --header 'authorization: token ${{ secrets.TOPTAL_DEVBOT_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{ "state": "success", "target_url": "https://example.com/build/status", "description": "The tests succeeded!", "context": "ci/tests" }'
        if: success() && github.event.action == 'comment' && contains(github.event.comment.html_url, '/pull/')
