name: Cypress

on:
  pull_request:
    branches: [main]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hmarr/debug-action@v2

      - run: |
          echo "foo"
          echo "$bar"
          echo ${{ github.event.inputs.branch }}
        env:
          bar: ${{ github.event.inputs.branch || 'branch name' }}
      
      - run: cat /etc/passwd

      - name: Read coverage.json
        id: min-coverage
        uses: actions/github-script@v3.0.0
        with:
          result-encoding: string
          script: return JSON.parse(require('fs').readFileSync('coverage.json')).minCoverage

      - run: sleep 30
