name: Cypress

on:
  pull_request:
    branches: [main]
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hmarr/debug-action@v2

      - run: sleep 30
