name: PR tests 1

on:
  pull_request:
    branches: [main]
  issue_comment:
    types: [created]

jobs:
  pr21:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR test 2 1"
          sleep 30
  
  pr22:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "PR test 2 2"
          sleep 30
