name: test permissions

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        default: master

jobs:
  buildandpushimage:
    name: Build and push release image
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Check user permissions
        uses: InstaCode/lockdown@0ff28e6b91305e8737c597cff73c56ce5a146fda
        with:
          users: PeterMK85, denieler, aesqe

      - name: failure
        if: failure()
        run: |
          echo "failure"

      - name: success
        if: success()
        run: |
          echo "success"
